apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-artifact-deployment
  labels:
    app: go-artifact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-artifact
  template:
    metadata:
      labels:
        app: go-artifact
    spec:
      containers:
      - name: go-artifact
        image: shahnishit/jenkins-docker:31
        ports:
        - containerPort: 80

